# generate a flow-chart of the workflow of phonetic researches

graph TD
A(smoothing) --> |B-spline|B(landmark registration)
B --> C(class analysis)
B --> |the principal component curves|D(functional PCA)
