# generate a flow-chart of the workflow of FDA

graph TD
A(Literature review) -->B(Experimental design)
B --> C(Data collection)
C --> D(Data management)
C --> E(Data analyses)
D --> F(Writing and editing)
E --> F(Writing and editing)
F --> G(Communication)
